marvel_api/models.py
from enum import unique
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from datetime import datetime
import uuid
from werkzeug.security import generate_password_hash, check_password_hash
import secrets 
from flask_login import LoginManager, UserMixin
from flask_marshmallow import Marshmallow


db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True)
    name = db.Column(db.String(150), unique = True)
    email = db.Column(db.String(150), nullable = False, unique = True)
    password = db.Column(db.String, nullable = False)
    token = db.Column(db.String, unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    character = db.relationship('Marvel', backref = 'owner', lazy = True)

    def __init__(self, email, password, token = '', id = ''):
        self.id = self.set_id()
        self.email = email
        self.password = self.set_password(password)
        self.token = self.set_token(24)

    def set_id(self):
        return str(uuid.uuid4())

    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash

    def set_token(self, length):
        return secrets.token_hex(length)


class Marvel(db.Model):
    id = db.Column(db.String, primary_key = True)
    name = db.Column(db.String(150))
    description = db.Column(db.String(200), nullable = True)
    comics_appeared_in = db.Column(db.Integer)
    super_power = db.Column(db.String(200))
    user_token = db.Column(db.String, db.ForeignKey('user.token'), nullable = False)
    
    
    def __init__(self, name, description, comics_appeared_in, super_power, user_token, id = ''):
        self.id = self.set_id()
        self.name = name
        self.description = description
        self.comics_appeared_in = comics_appeared_in
        self.super_power = super_power
        self.user_token = user_token

    def set_id(self):
        return (secrets.token_urlsafe())


class MarvelSchema(ma.Schema):
    class Meta:   
        fields = ['id', 'name', 'description', 'comics_appeared_in', 'super_power']

marvel_schema = MarvelSchema()
marvels_schema = MarvelSchema(many=True)

marvel_api/forms.py
from flask_wtf import FlaskForm
from flask_wtf.recaptcha import validators
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email

class UserLoginForm(FlaskForm):
    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators = [DataRequired()])
    submit_button = SubmitField()

marvel_api/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from marvel_api.routes import api
from flask_migrate import Migrate
from .models import db, login_manager, ma
from .helpers import JSONEncoder
from flask_cors import CORS
from .models import User



app = Flask(__name__)
app.config.from_object(Config)  
app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)
db.init_app(app)

login_manager.init_app(app)
ma.init_app(app)

login_manager.login_view = 'auth.signin'  
migrate = Migrate(app, db)

app.json_encoder = JSONEncoder

CORS(app)

marvel_api/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, login_required, logout_user
from marvel_api.forms import UserLoginForm
from marvel_api.models import User, db, check_password_hash


auth = Blueprint('auth', __name__, template_folder='auth_templates')


@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit(): 
        email = form.email.data
        password = form.password.data
        print([email, password])

        user = User(email, password)
        db.session.add(user)
        db.session.commit()

        flash(f'You have successfully created a user account {email}', 'user-created')
        return redirect(url_for('site.home'))

    return render_template('signup.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit(): 
        email = form.email.data
        password = form.password.data
        print([email, password])

        logged_user = User.query.filter(User.email == email).first()
        if logged_user and check_password_hash(logged_user.password, password):
            login_user(logged_user)
            flash('You are logged in.', 'auth-success')
            return redirect(url_for('site.home'))
        else:
            flash('Your Email/Password is incorrect', 'auth-failed')
            return redirect(url_for('auth.signin'))

    return render_template('signin.html', form = form)



@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))


def login_required(current_user):
    def logout():
        logout_user()
        return redirect(url_for('site.home'))
    if current_user.is_authenticated:
        return logout()

marvel_api/routes.py
from flask import Blueprint, json, request, jsonify
from marvel_api.helpers import token_required
from marvel_api.models import db, User, Marvel, marvel_schema, marvels_schema


api = Blueprint('api', __name__, url_prefix='/api')


@api.route('/getdata')
def getdata():
    return {'some_value': 52, 'another_value': 800}

#CREATE MARVEL API ENDPOINT
@api.route('/marvels', methods = ['POST'])
@token_required
def create_marvel(current_user_token):
    name = request.json['name']
    description = request.json['description']
    comics_appeared_in = request.json['comics_appeared_in']
    super_power = request.json['super_power']
    user_token = current_user_token.token

    print(f'TESTER: {current_user_token.token}')

    marvel = Marvel(name, description, comics_appeared_in, super_power, user_token = user_token)

    db.session.add(marvel)
    db.session.commit()

    response = marvel_schema.dump(marvel)
    return jsonify(response)

#Retrieve all marvel
@api.route('/marvels', methods = ['GET'])
@token_required
def get_marvels(current_user_token):
    owner = current_user_token.token
    marvels = Marvel.query.filter_by(user_token = owner).all()
    response = marvels_schema.dump(marvels)
    return jsonify(response)

#Retrieve single marvel endpoint
@api.route('/marvels/<id>', methods = ['GET'])
@token_required
def get_marvel(current_user_token, id):
    marvel = Marvel.query.get(id)
    response = marvel_schema.dump(marvel)
    return jsonify(response)


#Update a marvel by ID Enpoint
@api.route('/marvels/<id>', methods = ['POST'])
@token_required
def update_marvel(current_user_token, id):
    marvel = Marvel.query.get(id)
    print(marvel)
    if marvel:
        marvel.name = request.json['name']
        marvel.description = request.json['description']
        marvel.comics_appeared_in = request.json['comics_appeared_in']
        marvel.super_power = request.json['super_power']
        marvel.user_token = current_user_token.token
        db.session.commit()

        response = marvel_schema.dump(marvel)
        return jsonify(response)
    else:
        return jsonify({'Error': 'That Marvel does not exist!'})

#Delete marvel by ID
@api.route('/marvels/<id>', methods = ['DELETE'])
@token_required
def delete_marvel(current_user_token, id):
    marvel = Marvel.query.get(id)
    if marvel:
        db.session.delete(marvel)
        db.session.commit()

        response = marvel_schema.dump(marvel)
        return jsonify(response)
    else:
        return jsonify({'Error': 'That Marvel does not exist!'})

marvel_api/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site', __name__, template_folder='site_templates')



@site.route('/')
def home():
    return render_template('index.html')
    

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

marvel_api/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Marvel API</title>
</head>
<body>
    <!-- Navbar goes here -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div>
            <a class="navbar-brand" href="{{ url_for('site.home') }}">Marvel API</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav" id="horizontal-list">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('site.home') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('site.profile') }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                <li class="nav-item">
                    {% else %} 
                    <a class="nav-link" href="{{ url_for('auth.signin') }}">Signin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">Signup Free</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
        

    <!-- End of Nav -->
    {% block content %}
    {% endblock content %}
    

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

marvel_api/templates/form.html
<main class="container">
    <div class="row">
        <aside class="col-12 col-md-6">
            <h2>Create Your Free Account</h2>
            <!--Most HTML producted by Flask Form Object-->
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    <fieldset id="email-field">
                        {{ form.email.label }}
                        {{ form.email(class = "form-control", placeholder = "Enter Email") }}
                    </fieldset>
                    <fieldset id="password-field">
                        {{ form.password.label }}
                        {{ form.password(class = "form-control", placeholder = "Enter Password") }}
                    </fieldset>

                    <!--Submit Field Button Here-->
                    {{ form.submit_button(class = "btn btn-success btn block") }}
                </div>
            </form>
        </aside>
    </div>
</main>